version: 2
updates:
  - package-ecosystem: pub
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: pub
    directory: "example/"
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
