// import 'package:flutter/cupertino.dart' show CupertinoTextField;
// import 'package:flutter/material.dart' show TextField;

// const TextField({
//     Key key,
//     this.controller,
//     this.focusNode,
//     this.decoration = const InputDecoration(),
//     TextInputType keyboardType,
//     this.textInputAction,
//     this.textCapitalization = TextCapitalization.none,
//     this.style,
//     this.textAlign = TextAlign.start,
//     this.textDirection,
//     this.autofocus = false,
//     this.obscureText = false,
//     this.autocorrect = true,
//     this.maxLines = 1,
//     this.maxLength,
//     this.maxLengthEnforced = true,
//     this.onChanged,
//     this.onEditingComplete,
//     this.onSubmitted,
//     this.inputFormatters,
//     this.enabled,
//     this.cursorWidth = 2.0,
//     this.cursorRadius,
//     this.cursorColor,
//     this.keyboardAppearance,
//     this.scrollPadding = const EdgeInsets.all(20.0),
//     this.enableInteractiveSelection = true,
//     this.onTap,
//   }) : assert(textAlign != null),
//        assert(autofocus != null),
//        assert(obscureText != null),
//        assert(autocorrect != null),
//        assert(maxLengthEnforced != null),
//        assert(scrollPadding != null),
//        assert(maxLines == null || maxLines > 0),
//        assert(maxLength == null || maxLength > 0),
//        keyboardType = keyboardType ?? (maxLines == 1 ? TextInputType.text : TextInputType.multiline),
//        assert(enableInteractiveSelection != null),
//        super(key: key);

// const CupertinoTextField({
//     Key key,
//     this.controller,
//     this.focusNode,
//     this.decoration = _kDefaultRoundedBorderDecoration,
//     this.padding = const EdgeInsets.all(6.0),
//     this.placeholder,
//     this.prefix,
//     this.prefixMode = OverlayVisibilityMode.always,
//     this.suffix,
//     this.suffixMode = OverlayVisibilityMode.always,
//     this.clearButtonMode = OverlayVisibilityMode.never,
//     TextInputType keyboardType,
//     this.textInputAction,
//     this.textCapitalization = TextCapitalization.none,
//     this.style = _kDefaultTextStyle,
//     this.textAlign = TextAlign.start,
//     this.autofocus = false,
//     this.obscureText = false,
//     this.autocorrect = true,
//     this.maxLines = 1,
//     this.maxLength,
//     this.maxLengthEnforced = true,
//     this.onChanged,
//     this.onEditingComplete,
//     this.onSubmitted,
//     this.inputFormatters,
//     this.enabled,
//     this.cursorWidth = 2.0,
//     this.cursorRadius,
//     this.cursorColor = CupertinoColors.activeBlue,
//     this.keyboardAppearance,
//     this.scrollPadding = const EdgeInsets.all(20.0),
//   }) : assert(textAlign != null),
//        assert(autofocus != null),
//        assert(obscureText != null),
//        assert(autocorrect != null),
//        assert(maxLengthEnforced != null),
//        assert(scrollPadding != null),
//        assert(maxLines == null || maxLines > 0),
//        assert(maxLength == null || maxLength > 0),
//        assert(clearButtonMode != null),
//        assert(prefixMode != null),
//        assert(suffixMode != null),
//        keyboardType = keyboardType ?? (maxLines == 1 ? TextInputType.text : TextInputType.multiline),
//        super(key: key);

// REMEMBER to update readme
