name: build-test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

concurrency:
  # Cancels the workflow
  # when another event in the same context happens.
  # If it's a PR, context is the pull request number.
  # Otherwise, it uses the Git reference(branch or tag name).
  group: >
    ${{ github.workflow }}
    ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.runner }} / ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false # Important
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
        target: [android, web] # On all platforms
        include:
          # Specify targets for each platform
          - runner: ubuntu-latest
            target: linux
          - runner: windows-latest
            target: windows
          - runner: macos-latest
            target: macos
          - runner: macos-latest
            target: ios

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Setup Ninja and GTK3 toolchain (Only Linux target)
        if: matrix.target == 'linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Setup Java toolchain (Only Android target)
        if: matrix.target == 'android'
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"
          cache: "gradle"

      - name: Build the example app
        if: matrix.target == 'linux'
        working-directory: example/
        run: flutter build linux --verbose

      - name: Build the example app
        if: matrix.target == 'android'
        working-directory: example/
        run: |
          flutter build apk --verbose
          flutter build appbundle --verbose

      - name: Build the example app
        if: matrix.target == 'windows'
        working-directory: example/
        run: flutter build windows --verbose

      - name: Build the example app
        if: matrix.target == 'macos'
        working-directory: example/
        run: flutter build macos --verbose

      - name: Build the example app
        if: matrix.target == 'ios'
        working-directory: example/
        run: flutter build ios --verbose --no-codesign

      - name: Build the example app
        if: matrix.target == 'web'
        working-directory: example/
        run: flutter build web --verbose
